################################################################################
#+
#  Module:	$KSSDIR/kcwi/scripts/Makefile
#
#  Revisions:
#
#  Author:	Jason Weiss, Don Neill
#
#  Date:	2014/09/02
#
#  Description:	Top level Makefile for KCWI Scripts
#-
################################################################################

#DIRS	= procs mira util control operations widgets
DIRS	= Calibration Detector Display Frames Images Stages Utils PowerAndInit Tel KCWIConfManager

#  This is a release point. Define version macros to override values inherited
#  from the environment.

override SYSNAM = kss/kcwi/scripts/python
override VERNUM = 1.0.1


#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
